---
openapi: 3.0.1
x-zally-ignore: [105, 104, 101]
info:
  title: NS Registrations API
  description: Download Registrations Artifacts
  contact:
    name: VolkerWessels Telecom
    email: info@vwt.digital
    url: http://www.volkerwesselstelecom.com
  license:
    name: GNU GPLv3
    url: 'https://www.gnu.org/licenses/gpl.txt'
  version: 1.0.0
  x-audience: company-internal
  x-api-id: unspecified
servers:
  - url: /
paths:
  /surveys/{survey_id}/registrations/{registration_id}/images:
    get:
      summary: Get list of fotos per registrations
      description: Fotos per filled surveys
      operationId: get_registrations_attachments
      security:
        - Surveys: [surveys]
      parameters:
        - $ref: '#/components/parameters/surveyId'
        - $ref: '#/components/parameters/registrationId'
      responses:
        '200':
          description: Download Complete
          content:
            application/json:
              examples:
                attachment:
                  value:
                    6989e7038051475cd2c9f3236f4c0001957e1a: >-
                      [ 3, 4, 5]
        '404':
          description: Download Failed
      x-openapi-router-controller: openapi_server.controllers.surveys_controller
    x-eac-ignore: true
  /surveys/{survey_id}/registrations/{registration_id}/images/archives:
    get:
      summary: Download a single of registrations image folder as a zip archive
      description: Download an archive of images
      operationId: get_single_images_archive
      security:
        - Surveys: [surveys]
      parameters:
        - $ref: '#/components/parameters/surveyId'
        - $ref: '#/components/parameters/registrationId'
      responses:
        '200':
          description: Download Success
          content:
            application/zip:
              schema:
                $ref: '#/components/schemas/zipFile'
        '404':
          description: Download Failed
      x-openapi-router-controller: openapi_server.controllers.surveys_controller
    x-eac-ignore: true
  /surveys/{survey_id}/registrations/csvfiles:
    get:
      summary: Retrieve a csv file
      description: Get ready registrations
      operationId: get_registrations_as_csv
      parameters:
        - $ref: '#/components/parameters/storagePrefix'
      security:
        - Surveys: [surveys]
      responses:
        '200':
          description: Download Success
          content:
            text/csv:
              schema:
                $ref: '#/components/schemas/csvFile'
        '401':
          description: Not authenticated
        '403':
          description: Access token does not have the required scope
        '404':
          description: Not found
      x-openapi-router-controller: openapi_server.controllers.surveys_controller
    x-eac-ignore: true
  /surveys/{survey_id}/registrations/archives:
    get:
      summary: Retrieve a zip file
      description: Get ready registrations
      operationId: get_registrations_as_zip
      parameters:
        - $ref: '#/components/parameters/storagePrefix'
      security:
        - Surveys: [surveys]
      responses:
        '200':
          description: Download Success
          content:
            application/zip:
              schema:
                $ref: '#/components/schemas/zipFile'
        '401':
          description: Not authenticated
        '403':
          description: Access token does not have the required scope
        '404':
          description: Not found
      x-openapi-router-controller: openapi_server.controllers.surveys_controller
    x-eac-ignore: true
  /surveys/{survey_id}/registrations:
    get:
      summary: Get a list of available registrations
      description: A list of registrations
      operationId: get_registrations_list
      security:
        - Surveys: [surveys]
      parameters:
        - $ref: '#/components/parameters/storagePrefix'
      responses:
        '200':
          description: List OK
          content:
            application/json:
              examples:
                registrations:
                  value:
                    6989e703805147659fb50edea7792c79: 6
        '404':
          description: List Not Accessed
      x-openapi-router-controller: openapi_server.controllers.surveys_controller
    x-eac-ignore: true
  /surveys:
    get:
      description: Get all forms available
      operationId: get_forms_list
      security:
        - Surveys: [surveys]
      responses:
        '200':
          description: List OK
          content:
            application/json:
              examples:
                registrations:
                  value:
                    6989e703805147659fb50edea7792c79: 6
        '404':
          description: List Not Accessed
      x-openapi-router-controller: openapi_server.controllers.surveys_controller
    x-eac-ignore: true
  /surveys/{nonce}:
    get:
      description: Download previously requested information
      operationId: get_surveys_nonce
      parameters:
        - $ref: '#/components/parameters/nonce'
      responses:
        '200':
          description: download started
          content:
            application/zip:
              schema:
                $ref: '#/components/schemas/zipFile'
            text/csv:
              schema:
                $ref: '#/components/schemas/csvFile'
        '404':
          description: Not found
      x-openapi-router-controller: openapi_server.controllers.surveys_controller
    x-eac-ignore: true
components:
  schemas:
    zipFile:
      type: string
      format: binary
    csvFile:
      type: string
      example: |-
        Name,Age,Location
        John Doe,103,Venus
  parameters:
    storagePrefix:
      name: survey_id
      in: path
      description: A folder name to where a particular form/survey is saved in Storage
      required: true
      schema:
        type: string
    surveyId:
      name: survey_id
      in: path
      description: A unique survey or form identifier
      required: true
      schema:
        type: string
    registrationId:
      name: registration_id
      in: path
      description: A unique filled survey or registration identifier
      required: true
      schema:
        type: integer
    nonce:
      name: nonce
      in: path
      description: Unique download identifier
      required: true
      schema:
        type: string
        format: uuid
  securitySchemes:
    Surveys:
      type: oauth2
      description: OAuth through Azure AD
      flows:
        authorizationCode:
          authorizationUrl: >-
            https://login.microsoftonline.com/be36ab0a-ee39-47de-9356-a8a501a9c832/oauth2/v2.0/authorize
          tokenUrl: >-
            https://login.microsoftonline.com/be36ab0a-ee39-47de-9356-a8a501a9c832/oauth2/v2.0/token
          scopes:
            surveys: Grant Download Access
      x-tokenInfoFunc: openapi_server.controllers.security_controller_.info_from_OAuth2AzureAD
      x-scopeValidateFunc: connexion.decorators.security.validate_scope
