runtime: python37

entrypoint: gunicorn -b :$PORT app:main

env_variables:
  BUCKET_NAME: "vwt-d-gew1-ns-surveys-registrations-stg"

endpoints_api_service:
  name: vwt-d-gew1-ns-surveys.appspot.com
  rollout_strategy: managed
