steps:
- name: 'ubuntu'
  args:
  - 'bash'
  - '-c'
  - |
    cp config/${PROJECT_ID}/config.py app

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - 'gcloud app create --region=europe-west1 || exit 0'

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'gcloud app'
  - 'deploy'
  dir: 'app'
