steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    curl https://vwt-digital.github.io/project-company-data.github.io/gcp-templates/deploy_data_catalog.sh | bash /dev/stdin $PROJECT_ID-dcat-deploy config/${PROJECT_ID}/data_catalog.json $PROJECT_ID

- name: 'gcr.io/cloud-builders/git'
  args:
  - 'clone'
  - '--branch=${BRANCH_NAME}'
  - 'https://github.com/vwt-digital/ns-surveysapi.git'

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - 'gcloud endpoints services deploy openapi.yaml'
  
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - 'gcloud app create --region=europe-west1'

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'gcloud app'
  - 'deploy'
  dir: 'app'


