swagger: '2.0'
info:
  title: Surveys API
  description: Download A CSV file
  contact:
    name: VolkerWessels Telecom
    email: info@vwt.digital
  license:
    name: GNU GPLv3
    url: 'https://www.gnu.org/licenses/gpl.txt'
  version: 1.0.0
host: 'vwt-d-gew1-ns-surveys.appspot.com'
paths:
  /get_surveys:
    get:
      summary: Retrieve a csv file
      description: Get ready registrations
      operationId: get_survey_as_csv
      responses:
        '200':
          description: 'Download Success: OK'
          schema:
            type: string
#      security:
#        -
#          Surveys:
#            - surveys.download
#securityDefinitions:
#  Surveys:
#    type: oauth2
#    description: 'OAuth2 security'
#    flow: accessCode
#    authorizationUrl: 'https://login.microsoftonline.com/be36ab0a-ee39-47de-9356-a8a501a9c832/oauth2/v2.0/authorize'
#    tokenUrl: 'https://login.microsoftonline.com/be36ab0a-ee39-47de-9356-a8a501a9c832/oauth2/v2.0/token'
#    scopes:
#      download:surveys: Grant Download Access
#security:
#  -
#    Surveys:
#      - surveys.download
