runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

env_variables:
  BUCKET: "vwt-d-gew1-ns-surveys-registrations-stg"

endpoints_api_service:
  name: vwt-d-gew1-ns-surveys.appspot.com
  rollout_strategy: managed
